apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: microservice-role
  namespace: urbanflow
  labels:
    app.kubernetes.io/part-of: urbanflow
    app.kubernetes.io/component: rbac
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["app-config"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["app-secrets", "mysql-secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: frontend-role
  namespace: urbanflow
  labels:
    app.kubernetes.io/part-of: urbanflow
    app.kubernetes.io/component: rbac
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["app-config"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["app-secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mysql-backup-role
  namespace: urbanflow
  labels:
    app.kubernetes.io/part-of: urbanflow
    app.kubernetes.io/component: rbac
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["app-config"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["app-secrets", "mysql-secrets"]
    verbs: ["get"]
