apiVersion: v1
kind: ServiceAccount
metadata:
  name: ticketing-service
  namespace: urbanflow
  labels:
    app.kubernetes.io/name: ticketing-service
    app.kubernetes.io/part-of: urbanflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: passenger-service
  namespace: urbanflow
  labels:
    app.kubernetes.io/name: passenger-service
    app.kubernetes.io/part-of: urbanflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gps-service
  namespace: urbanflow
  labels:
    app.kubernetes.io/name: gps-service
    app.kubernetes.io/part-of: urbanflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service
  namespace: urbanflow
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/part-of: urbanflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-service
  namespace: urbanflow
  labels:
    app.kubernetes.io/name: analytics-service
    app.kubernetes.io/part-of: urbanflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: urbanflow
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: urbanflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-backup
  namespace: urbanflow
  labels:
    app.kubernetes.io/name: mysql-backup
    app.kubernetes.io/part-of: urbanflow
    app.kubernetes.io/component: backup
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/urbanflow-mysql-backup-role
