apiVersion: v1
kind: Service
metadata:
  name: passenger-service
  namespace: urbanflow
  labels:
    app.kubernetes.io/name: passenger-service
    app.kubernetes.io/part-of: urbanflow
    app.kubernetes.io/component: microservice
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: passenger-service
  ports:
    - name: http
      port: 3002
      targetPort: http
      protocol: TCP
